Fix kmip test
Default pip installed pykmip-server generates the following error:

sqlalchemy.exc.InvalidRequestError: Implicitly combining column managed_objects.uid with column crypto_objects.uid under attribute 'unique_identifier'.  Please configure one or more attributes for these same-named columns explicitly.

See https://github.com/OpenKMIP/PyKMIP/issues/687 for this workaround

Signed-off-by: Alexander Indenbaum <aindenba@redhat.com>
(cherry picked from commit 1667922bc43ff056ac1352ddafd992789e8f0766)