Also install setuptools
Without setuptools, running operator-courier fails with:

```
Traceback (most recent call last):
  File "/Users/zregvart/work/croz/noobaa/noobaa-operator/build/_output/venv/bin/operator-courier", line 5, in <module>
    from operatorcourier.cli import main
  File "/Users/zregvart/work/croz/noobaa/noobaa-operator/build/_output/venv/lib/python3.13/site-packages/operatorcourier/cli.py", line 2, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
make: *** [gen-olm] Error 1
```

Signed-off-by: Zoran Regvart <zoran@regvart.com>
(cherry picked from commit 06528c32259efae54ba1483dbaa81fa2ccd7fed2)